version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      test-packages:
        patterns:
          - "AutoFixture*"
          - "coverlet.*"
          - "FluentAssertions"
          - "Microsoft.NET.Test.Sdk"
          - "Moq"
          - "xunit*"

  - package-ecosystem: "docker"
    directory: "/src/Rafatz.SumUpReceiptForwarder.Worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
