services:
  sumup-receipt-forwarder:
    image: ghcr.io/mstroppel/sumup-receipt-forwarder:latest
    restart: unless-stopped
    environment:
      - WORKER_DELAY=15
      - SUMUP_ACCOUNT_ID=ABC123456789
      - SUMUP_API_KEY=secret-key
      - SMTP_HOST=mail.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=password
      - SMTP_USE_TLS=true
      - SENDER_EMAIL=sender@example.com
      - RECIPIENT_EMAIL_CASH=receiver-cash@example.com
      - RECIPIENT_EMAIL_CARD=receiver-card@example.com
    volumes:
      - receipt-data:/app/data

volumes:
  receipt-data:
